# Default options
- name: SETTING DEFAULT keyboard_model
  ansible.builtin.set_fact:
    keyboard_model: pc105
  when: keyboard_model is not defined
- name: SETTING DEFAULT keyboard_layout
  ansible.builtin.set_fact:
    keyboard_layout: us
  when: keyboard_layout is not defined
- name: SETTING DEFAULT keyboard_variant
  ansible.builtin.set_fact:
    keyboard_variant: ""
  when: keyboard_variant is not defined
# Configuring keyboard
- name: CONFIGURING KEYBOARD
  ansible.builtin.lineinfile:
    dest: "/etc/default/keyboard"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "^\\s*#?\\s*XKBMODEL", line: "XKBMODEL=\"{{ keyboard_model }}\""}
    - {regexp: "^\\s*#?\\s*XKBLAYOUT", line: "XKBLAYOUT=\"{{ keyboard_layout }}\""}
    - {regexp: "^\\s*#?\\s*XKBVARIANT", line: "XKBVARIANT=\"{{ keyboard_variant }}\""}
