# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
namespace: dainok
name: courses
version: "0.0.18"
readme: README.md
authors:
  - Andrea Dainese (@dainok)
description: Andrea Dainese's Ansible collection."
license:
  - "GPL-3.0-or-later"
tags:
  - eda
homepage: https://github.com/dainok/ansible-collection
repository: https://github.com/dainok/ansible-collection
issues: https://github.com/dainok/ansible-collection/issues
documentation: https://github.com/dainok/ansible-collection
dependencies:
  cisco.ios: ">=8.0.0"
build_ignore:
  - .ansible-lint
  - .bandit.yml
  - .gitignore
  - .flake8
  - .markdownlint.yaml
  - .pylintrc
  - .pydocstyle.ini
  - .pre-commit-config.yaml
  - .yamllint.yml
  - .yamllint
  - .yamlfmt
  - ansible-navigator.log
  - inventory.yml
  - playbook-action.yml
  - playbook-rulebook-syslog.yml
  - requirements.txt
  - venv
