# Configuring /etc/hostname
- name: CONFIGURING HOSTNAME
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short | lower }}"
    use: debian
# Configuring /etc/hosts
- name: CONFIGURING HOSTS FILE
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "^\\s*#?\\s*127.0.0.1", line: "127.0.0.1       localhost"}
    - {regexp: "^\\s*#?\\s*::1", line: "::1             localhost ip6-localhost ip6-loopback"}
    - {regexp: "^\\s*#?\\s*ff02::1", line: "ff02::1         ip6-allnodes"}
    - {regexp: "^\\s*#?\\s*ff02::2", line: "ff02::2         ip6-allrouters"}
    - {regexp: "^\\s*#?\\s*127.0.1.1", line: "127.0.1.1       {{ inventory_hostname_short }} {{ inventory_hostname }}"}
