galaxy_info:
  role_name: linux_systemd_enable_disable
  author: Andrea Dainese
  description: "This role enable and disable services using systemd."
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.15.0"
