# Usage: ansible-rulebook --rulebook playbook-rulebook-syslog.yml -i inventory.yml --verbose
- name: Listen for events via syslog
  hosts: all
  sources:
    - dainok.common.syslog:
        host: 0.0.0.0
        port: 1514
  rules:
    - name: CISCO - configured device
      condition: event.message is match("Configured from.*", ignorecase=true)
      action:
        run_playbook:
          name: playbook-action.yml
        debug:
          msg: "Received: {{ event.message }}"
