# Default options
- name: SETTING DEFAULT ssh_root_login
  ansible.builtin.set_fact:
    ssh_root_login: prohibit-password
  when: ssh_root_login is not defined
- name: SETTING DEFAULT ssh_client_alive_interval
  ansible.builtin.set_fact:
    ssh_client_alive_interval: 14400
  when: ssh_client_alive_interval is not defined
- name: SETTING DEFAULT ssh_client_alive_count
  ansible.builtin.set_fact:
    ssh_client_alive_count: 5
  when: ssh_client_alive_count is not defined
# Install required packages
- name: INSTALLING PACKAGES
  ansible.builtin.apt:
    name:
      - openssh-server
      - openssh-sftp-server
      - openssh-client
    update_cache: false
    force_apt_get: true
    state: latest
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: install
# Configuring OpenSSH Server
- name: CONFIGURING OPENSSH SERVER
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "^\\s*#?\\s*PermitRootLogin", line: "PermitRootLogin {{ ssh_root_login }}"}
    - {regexp: "^\\s*#?\\s*ClientAliveInterval", line: "ClientAliveInterval {{ ssh_client_alive_interval }}"}
    - {regexp: "^\\s*#?\\s*ClientAliveCountMax", line: "ClientAliveCountMax {{ ssh_client_alive_count }}"}
  notify: DEBIAN-SSH-RESTART
