#!/usr/bin/env ansible-playbook
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: BACKUP RUNNING CONFIG
      cisco.ios.ios_config:
        backup: true
        backup_options:
          filename: "{{ ansible_host }}-backup.cfg"
          dir_path: /opt/ansible/backup
