# Mandatory options
- name: CHECK vlans
  ansible.builtin.fail:
    msg: vlans is not set
  when: vlans is not defined
# Convert a list of VLAN to be used with ios_vlans module
- name: SETTING VLAN LIST
  ansible.builtin.set_fact:
    vlans_config_list: "{{ vlans_config_list | default([]) + [{'vlan_id': item.id, 'name': item.name}] }}"
  with_items: "{{ vlans }}"
# Add VLANs
- name: ADDING VLANS
  cisco.ios.ios_vlans:
    config: "{{ vlans_config_list }}"
    state: merged
